# SMTP email settings (used by EmailService)
# For testing, you can use Gmail with an App Password
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=tamiadeniji@gmail.com
mail.smtp.password=cnko ynkh gmxw kuf
mail.smtp.auth=true
mail.smtp.starttls.enable=true
